UPDATE teams
SET
games_played=games_played,
wins=wins,
loss=loss,
ties=ties,
points=points,
goals_for=goals_for,
goals_against=goals_against,
pp_attempts=pp_attempts,
pp_goals=pp_goals,
pp_min=pp_min,
pk_attempts=pk_attempts,
pk_goals=pk_goals,
pk_min=pk_min,
penalty_minutes=penalty_minutes,
sh_goals=sh_goals,
home_wins=home_wins,
home_loss=home_loss,
home_ties=home_ties,
road_wins=road_wins,
road_loss=road_loss,
road_ties=road_ties,
div_win=div_win,
div_loss=div_loss,
div_tie=div_tie,
ot_win=ot_win,
ot_loss=ot_loss,
lead_after_two_wins=lead_after_two_wins,
lead_after_two_loss=lead_after_two_loss,
lead_after_two_ties=lead_after_two_ties,
trail_after_two_wins=trail_after_two_wins,
trail_after_two_loss=trail_after_two_loss,
trail_after_two_ties=trail_after_two_ties,
even_after_two_wins=even_after_two_wins,
even_after_two_loss=even_after_two_loss,
even_after_two_ties=even_after_two_ties,
long_win_streak=long_win_streak,
shots_for=shots_for,
shots_against=shots_against,
face_off_won=face_off_won,
face_off_lost=face_off_lost,
corner_won=corner_won,
corner_lost=corner_lost,
pass_complete=pass_complete,
pass_incomplete=pass_incomplete,
empty_net=empty_net,
shut_outs=shut_outs
WHERE team_name=team_name AND playing_year=playing_year AND season_type=season_type;

\copy teams (team_name, games_played, wins, loss, ties, points, goals_for, goals_against, pp_attempts, pp_goals, pp_min, pk_attempts, pk_goals, pk_min, penalty_minutes, sh_goals, home_wins, home_loss, home_ties, road_wins, road_loss, road_ties, div_win, div_loss, div_tie, ot_win, ot_loss, lead_after_two_wins, lead_after_two_loss, lead_after_two_ties, trail_after_two_wins, trail_after_two_loss, trail_after_two_ties, even_after_two_wins, even_after_two_loss, even_after_two_ties, long_win_streak, shots_for, shots_against, face_off_won, face_off_lost, corner_won, corner_lost, pass_complete, pass_incomplete, empty_net, shut_outs, playing_year, season_type) FROM '/Users/jeffkwok/Desktop/CHA-Hockey-app-server/postgres/seed/teamStats.tsv'

